### PR TITLE
New features for better UX

### PR DESCRIPTION
**Pull request by Hacksore**
This will allow for a `customCommitMessage` and a `ticketRegex` to extract the ticket number from the feature branch.

~~WIP for now until #1 is merged.~~

❤️ ❤️ ❤️ ❤️ ❤️ 

cc @maxdemaio 🫶

### CODE REVIEW

**Comment by maxdemaio** [comment]
Note: we'll rebase once #1 is in so it'll reflect our work

**Comment by Borwe** [comment]
Yeah this looks like cool feature to add :+1:

**Comment by maxdemaio** [comment]
> Yeah this looks like cool feature to add 👍

I think all of our changes are all set!

**Comment by Borwe** [comment]
Looks good for merging, BTW, mind adding like something on the README.md that explains how one can use this feature?

**Comment by maxdemaio** [comment]
> Looks good for merging, BTW, mind adding like something on the README.md that explains how one can use this feature?

Yes I can add a commit in the `README.md`, I'll drop a comment here when that's done!

**Comment by maxdemaio** [comment]
@Borwe Should be all set with 83e22f1c60ee4476e5280bec0140e86236c13e3a!

**Pull request merged**
